import { LLMProvider, GenerateRequest, GenerateResponse, LLMProviderCapability } from '@gh-ai-workflows/core';
import { ProviderError, RateLimitError, AuthenticationError, InvalidRequestError } from '@gh-ai-workflows/core';
import { Logger } from '@gh-ai-workflows/core';

export class GeminiProvider implements LLMProvider {
  readonly providerId = 'gemini';
  readonly capabilities: LLMProviderCapability = {
    capabilities: new Set(['json_mode', 'streaming', 'function_calling', 'vision']),
    maxTokens: 8192,
    contextWindow: 1000000,
  };

  constructor(private config: { apiKey: string; model: string }) {}

  async generate(request: GenerateRequest): Promise<GenerateResponse> {
    try {
      if (!this.config.apiKey) throw new Error('Missing API Key');

      const url = `https://generativelanguage.googleapis.com/v1beta/models/${this.config.model}:generateContent?key=${this.config.apiKey}`;

      const body: Record<string, unknown> = {
        contents: [
          {
            role: 'user',
            parts: [{ text: request.prompt }],
          },
        ],
        generationConfig: {
          temperature: request.temperature ?? 0.7,
          maxOutputTokens: request.maxTokens ?? this.capabilities.maxTokens,
          responseMimeType: request.jsonMode ? 'application/json' : 'text/plain',
        },
      };

      if (request.systemPrompt) {
        body.system_instruction = {
          parts: [{ text: request.systemPrompt }],
        };
      }

      if (request.stopSequences && request.stopSequences.length > 0) {
        body.generationConfig.stopSequences = request.stopSequences;
      }

      Logger.debugProvider(this.providerId, 'REQUEST', body);

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        const errorMessage = errorData.error?.message || response.statusText;
        throw new Error(`${response.status}: ${errorMessage}`);
      }

      const data: unknown = await response.json();
      Logger.debugProvider(this.providerId, 'RESPONSE', data);

      const candidate = (data as Record<string, unknown>)?.candidates?.[0];

      if (!candidate) {
        throw new Error('No candidate response generated by Gemini');
      }

      // Explicitly filter out thought blocks to ensure we only get the final answer
      const text = candidate.content?.parts
        ?.filter((part: unknown) => (part as Record<string, unknown>).thought !== true)
        .map((part: unknown) => (part as Record<string, unknown>).text || '')
        .join('\n')
        .trim() || '';
      
      const usage = data.usageMetadata || candidate.usageMetadata || {
        promptTokenCount: 0,
        candidatesTokenCount: 0,
        totalTokenCount: 0,
      };

      return {
        text,
        usage: {
          promptTokens: usage.promptTokenCount,
          completionTokens: usage.candidatesTokenCount,
          totalTokens: usage.totalTokenCount,
        },
        finishReason: this.mapFinishReason(candidate.finishReason),
      };
    } catch (e: unknown) {
      throw this.normalizeError(e);
    }
  }

  private mapFinishReason(reason: string): GenerateResponse['finishReason'] {
    switch (reason) {
      case 'STOP': return 'stop';
      case 'MAX_TOKENS': return 'length';
      case 'SAFETY': return 'content_filter';
      case 'OTHER': return 'unknown';
      default: return 'unknown';
    }
  }

  private normalizeError(e: unknown): Error {
    const message = e instanceof Error ? e.message : String(e);
    if (message.includes('429')) return new RateLimitError(message);
    if (message.includes('401') || message.includes('403')) return new AuthenticationError(message);
    if (message.includes('400')) return new InvalidRequestError(message);
    return new ProviderError(message);
  }
}
