import { writeFileSync, existsSync } from 'node:fs';
import { mkdirSync } from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { GitHubClient } from '@platform/github';
import { ProviderRegistry } from '@core/registry';
import { PromptEngine } from '@core/prompt-engine';
import { Logger } from '@core/telemetry';
import { summarizeDiff } from '@core/diff-summarizer';
import { registerAllProviders } from '@platform/llm';
import { generateStructured } from '@core/structured-generation';
import { DocSyncSchema, DocSyncInputs } from './schema';
import { collectDocs } from '@core/utils/file-system';
import { DocSyncPrompt } from './prompt';
import { createRunner } from '@core/workflow-runner';
import { runPipeline } from '@core/workflow-pipeline';
import type { PipelineInputs } from '@core/workflow-pipeline';
import type { DocSync } from './schema';

function runGitCommand(command: string) {
  try {
    return execSync(command, { encoding: 'utf8' }).trim();
  } catch (error: any) {
    Logger.error(`Git command failed: ${command}\nError: ${error.stderr || error.message}`);
    throw error;
  }
}

async function findAuditBaseline(gh: GitHubClient, owner: string, repo: string, lookback: number): Promise<string> {
  Logger.log('Searching for last merged audit PR...');
  try {
    const mergedPRs = await gh.listMergedPRs(owner, repo);
    const auditPR = mergedPRs.find(pr =>
      pr.merged_at &&
      (pr.title.startsWith('docs: sync documentation') || pr.title.includes('Documentation Sync'))
    );
    if (auditPR) {
      Logger.log(`Found last audit PR #${auditPR.number}. Using its merge commit as baseline.`);
      const prDetails = await gh.request<any>(`/repos/${owner}/${repo}/pulls/${auditPR.number}`);
      return prDetails.merge_commit_sha;
    }
  } catch (e) {
    Logger.warn(`Failed to search PR history: ${e instanceof Error ? e.message : String(e)}`);
  }
  Logger.log(`No audit PR found. Falling back to lookback of ${lookback} commits.`);
  try {
    return runGitCommand(`git rev-list -n 1 HEAD~${lookback}`);
  } catch (e) {
    Logger.warn(`Lookback of ${lookback} commits failed. Falling back to first commit.`);
    return runGitCommand('git rev-list --max-parents=0 HEAD');
  }
}

async function applyDocChanges(result: DocSync, pullNumber: number | undefined, baseBranch: string) {
  if (result.changes.length === 0) {
    Logger.log('No documentation updates needed.');
    return false;
  }
  Logger.log('Applying changes to a sync branch...');
  const branchName = pullNumber ? `bot/docs-sync-${pullNumber}` : `bot/docs-sync-audit-${Date.now()}`;
  runGitCommand('git config user.name "github-actions[bot]"');
  runGitCommand('git config user.email "github-actions[bot]@users.noreply.github.com"');
  runGitCommand(`git checkout -B ${branchName} origin/${baseBranch}`);
  for (const change of result.changes) {
    const filePath = path.join(process.cwd(), change.path);
    const dirPath = path.dirname(filePath);
    if (change.action === 'create' || change.action === 'update') {
      if (!existsSync(dirPath)) mkdirSync(dirPath, { recursive: true });
      writeFileSync(filePath, change.content, 'utf8');
      Logger.log(`Updated: ${change.path}`);
    } else if (change.action === 'delete') {
      if (existsSync(filePath)) {
        runGitCommand(`git rm ${change.path}`);
        Logger.log(`Deleted: ${change.path}`);
      }
    }
  }
  runGitCommand('git add .');
  const commitMsg = pullNumber
    ? `docs: sync documentation for PR #${pullNumber}\n\n${result.summary}`
    : `docs: sync documentation audit\n\n${result.summary}`;
  runGitCommand(`git commit -m "${commitMsg.replace(/"/g, '\\"')}"`);
  runGitCommand(`git push origin ${branchName} --force`);
  return true;
}

async function createSyncPR(gh: GitHubClient, owner: string, repo: string, pullNumber: number | undefined, result: DocSync, baseBranch: string) {
  const prTitle = pullNumber
    ? `docs: sync documentation for PR #${pullNumber}`
    : 'docs: sync documentation audit';
  const prBody = `## 📄 Documentation Sync\n\n${result.summary}\n\n### Changes\n` +
    result.changes.map(c => `- ${c.action === 'create' ? '✅ Created' : c.action === 'update' ? '🔄 Updated' : '🗑️ Deleted'}: \`${c.path}\` (${c.explanation})`).join('\n') +
    '\n\n---\n_Auto-generated by Doc Sync Workflow_';
  const branchName = pullNumber ? `bot/docs-sync-${pullNumber}` : `bot/docs-sync-audit-${Date.now()}`;
  const existingPRs = await gh.listPRs(owner, repo, `${owner}:${branchName}`);
  if (existingPRs.length > 0) {
    const pr = existingPRs[0];
    await gh.updatePR(owner, repo, pr.number, prTitle, prBody);
    Logger.log(`Updated existing PR #${pr.number}`);
  } else {
    const newPR = await gh.createPR(owner, repo, prTitle, branchName, baseBranch, prBody);
    Logger.log(`Created new PR #${newPR.number}`);
  }
}

async function runAuditMode(inputs: DocSyncInputs & { githubClient?: GitHubClient }) {
  const { owner, repo, githubToken, apiKey, llm, model, docPattern, lookbackCommits, summaryLlm, summaryModel, githubClient: injectedClient } = inputs;
  const gh = injectedClient || new GitHubClient(githubToken);

  runGitCommand('git fetch origin main');
  runGitCommand('git checkout main');
  runGitCommand('git pull origin main');

  const baselineSha = await findAuditBaseline(gh, owner, repo, lookbackCommits ?? 10);
  Logger.log(`Baseline SHA: ${baselineSha}`);

  let codeDiff = runGitCommand(`git diff ${baselineSha}...HEAD -- . ':!dist'`);
  if (!codeDiff) {
    Logger.log('No changes found between baseline and HEAD.');
    return { synced: false, changes: [] };
  }

  if (summaryLlm && summaryModel) {
    registerAllProviders();
    const summaryProvider = ProviderRegistry.create(summaryLlm, { apiKey, model: summaryModel });
    codeDiff = await summarizeDiff(codeDiff, summaryProvider);
  }

  const projectDocs = collectDocs(docPattern ?? '.*\\.md');
  const prompt = PromptEngine.render(DocSyncPrompt, {
    code_diff: codeDiff,
    documentation: projectDocs || 'No documentation provided for these changes.',
  });

  registerAllProviders();
  const provider = ProviderRegistry.create(llm, { apiKey, model });

  const generationResult = await generateStructured(provider, DocSyncSchema, {
    prompt: prompt.user,
    systemPrompt: prompt.system,
  }, { maxRetries: 3, jsonMode: true });

  if (!generationResult.success) {
    throw new Error(`LLM Generation failed: ${generationResult.error}`);
  }

  const result = generationResult.data!;
  const synced = await applyDocChanges(result, undefined, 'main');
  if (synced) await createSyncPR(gh, owner, repo, undefined, result, 'main');
  return { synced, changes: result.changes };
}

export async function runDocSyncWorkflow(inputs: DocSyncInputs & { githubClient?: GitHubClient }) {
  const { owner, repo, pullNumber, debug, docPattern, apiKey, llm, model, githubToken, summaryLlm, summaryModel, githubClient: injectedClient } = inputs;

  if (debug) Logger.debug(`Running Doc Sync Workflow for ${owner}/${repo}${pullNumber ? `#${pullNumber}` : ' (Audit Mode)'}`);

  try {
    if (!pullNumber) return runAuditMode(inputs);

    const result = await runPipeline(
      { githubToken, llm, model, apiKey, owner, repo, pullNumber, debug, summaryLlm, summaryModel, githubClient: injectedClient },
      {
        promptDef: DocSyncPrompt,
        schema: DocSyncSchema,
        prepareVariables: async ({ codeDiff }) => ({
          code_diff: codeDiff,
          documentation: collectDocs(docPattern ?? '.*\\.md') || 'No documentation provided for these changes.',
        }),
        handleResult: async ({ gh }, docResult) => {
          const prDetails = await gh.getPRDetails(owner, repo, pullNumber);
          const baseBranch = prDetails.base.ref;
          const synced = await applyDocChanges(docResult, pullNumber, baseBranch);
          if (synced) await createSyncPR(gh, owner, repo, pullNumber, docResult, baseBranch);
        },
      },
    );

    return { synced: result.changes.length > 0, changes: result.changes };
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    Logger.error(`Workflow failed at step: ${message}`);
    throw error;
  }
}

if (process.env.NODE_ENV !== 'test') {
  createRunner(runDocSyncWorkflow).run();
}