name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/composites/setup
      - run: pnpm lint
      - run: pnpm test
