name: 'AI PR Review'

on:
  pull_request:
    types: [opened, labeled]

jobs:
  review:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || (github.event.action == 'labeled' && github.event.label.name == 'need-review')
    permissions:
      pull-requests: write
      contents: read
      issues: write
    steps:
      - uses: ../../composites/setup
      - name: 'Run AI PR Review'
        uses: ./workflows/pr-review
        with:
          llm: 'gemini'
          model: 'gemma-4-31b-it'
          api-key: ${{ secrets.GEMINI_API_KEY }}
          debug: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Remove label'
        if: github.event.action == 'labeled' && github.event.label.name == 'need-review'
        run: gh pr edit ${{ github.event.pull_request.number }} --remove-label 'need-review'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}